/**
 * lib/data.ts
 * Loads politician and lobby data from pre-generated JSON files.
 *
 * At build time, Next.js calls these functions to statically generate all pages.
 * Users get instant page loads - zero API calls at runtime.
 *
 * Data is generated by running: npm run pipeline
 * Output: data/politicians.json, data/lobbies.json
 *
 * If data files don't exist yet (first run), falls back to seed data
 * so the site builds successfully before you run the pipeline.
 */

import * as fs from 'fs';
import * as path from 'path';
import type { Politician, Lobby } from './types';

// --- Load politicians ---------------------------------------------------------

export async function getPoliticians(): Promise<Politician[]> {
  try {
    const filePath = path.join(process.cwd(), 'data', 'politicians.json');
    const raw = fs.readFileSync(filePath, 'utf-8');
    return JSON.parse(raw) as Politician[];
  } catch {
    console.warn('! data/politicians.json not found - using seed data. Run `npm run pipeline` to generate real data.');
    return getSeedPoliticians();
  }
}

export async function getPolitician(id: string): Promise<Politician | null> {
  const politicians = await getPoliticians();
  return politicians.find(p => p.id === id) || null;
}

export async function getPoliticianSlugs(): Promise<{ slug: string }[]> {
  const politicians = await getPoliticians();
  return politicians.map(p => ({ slug: p.id }));
}

// --- Load lobbies -------------------------------------------------------------

export async function getLobbies(): Promise<Lobby[]> {
  try {
    const filePath = path.join(process.cwd(), 'data', 'lobbies.json');
    const raw = fs.readFileSync(filePath, 'utf-8');
    return JSON.parse(raw) as Lobby[];
  } catch {
    return getSeedLobbies();
  }
}

export async function getLobby(id: string): Promise<Lobby | null> {
  const lobbies = await getLobbies();
  return lobbies.find(l => l.id === id) || null;
}

export async function getLobbyRecipients(lobbyId: string): Promise<Politician[]> {
  const politicians = await getPoliticians();
  return politicians
    .filter(p => p.lobbyMoney.some(l => l.lobbyId === lobbyId))
    .sort((a, b) => {
      const aAmt = a.lobbyMoney.find(l => l.lobbyId === lobbyId)?.amount || 0;
      const bAmt = b.lobbyMoney.find(l => l.lobbyId === lobbyId)?.amount || 0;
      return bAmt - aAmt;
    });
}

// --- Helpers ------------------------------------------------------------------

export function fmtMoney(n: number): string {
  if (n >= 1e9) return `$${(n / 1e9).toFixed(1)}B`;
  if (n >= 1e6) return `$${(n / 1e6).toFixed(2)}M`;
  if (n >= 1e3) return `$${(n / 1e3).toFixed(0)}K`;
  return `$${n}`;
}

export function partyColor(party: string): string {
  if (party.startsWith('Republican')) return '#ef4444';
  if (party.startsWith('Democrat')) return '#3b82f6';
  return '#a855f7';
}

export function partyShort(party: string): string {
  if (party.startsWith('Republican')) return 'REP';
  if (party.startsWith('Democrat')) return 'DEM';
  return 'IND';
}

export function riskLabel(score: number): { label: string; color: string; cssClass: string } {
  if (score >= 75) return { label: 'CRITICAL',  color: '#ef4444', cssClass: 'score-critical' };
  if (score >= 50) return { label: 'HIGH RISK', color: '#f97316', cssClass: 'score-high'     };
  if (score >= 25) return { label: 'ELEVATED',  color: '#eab308', cssClass: 'score-elevated' };
  return               { label: 'LOW RISK',   color: '#22c55e', cssClass: 'score-low'      };
}

// --- Seed data (used before pipeline runs) -----------------------------------

function getSeedPoliticians(): Politician[] {
  // Minimal seed data - just enough for the site to build
  // Replace with real data by running: npm run pipeline
  return [
    {
      id: 'exec-trump',
      name: 'Donald J. Trump',
      state: 'Florida',
      party: 'Republican',
      chamber: 'Executive',
      title: 'President',
      since: 2025,
      lobbyMoney: [
        { lobbyId: 'nra',   lobbyName: 'NRA',   amount: 31200000, intent: 'Oppose all gun control legislation', source: 'manual' },
        { lobbyId: 'api',   lobbyName: 'API',   amount: 75000000, intent: 'Withdraw from Paris Climate Accord, roll back EPA', source: 'manual' },
        { lobbyId: 'aipac', lobbyName: 'AIPAC', amount: 5200000,  intent: 'Move US Embassy to Jerusalem, fund Iron Dome', source: 'manual' },
      ],
      stockTrades: [
        { ticker: 'DJT', company: 'Trump Media & Technology Group', action: 'HOLD', amount: 4500000000, date: '2024-03-22', conflict: true, conflictNote: 'Holds majority stake in Truth Social parent company while serving as president', source: 'manual' },
        { ticker: 'TRUMP', company: 'Trump Meme Coin', action: 'BUY', amount: 620000000, date: '2025-01-18', conflict: true, conflictNote: 'Launched meme coin 2 days before inauguration while promising crypto deregulation', source: 'manual' },
      ],
      lawsuits: [
        { title: 'New York Criminal Conviction - 34 Felony Counts', year: 2024, type: 'Criminal - State', status: 'CONVICTED', outcome: 'Guilty on all 34 counts; first convicted US president', description: 'Convicted of falsifying business records to conceal hush money payments.', severity: 'high' },
        { title: 'E. Jean Carroll - Sexual Abuse & Defamation', year: 2023, type: 'Civil', status: 'CONVICTED', outcome: 'Liable; ordered to pay $83.3M', description: 'Federal jury found Trump liable for sexual abuse and defamation.', severity: 'high' },
        { title: 'NY AG - Trump Organization Fraud', year: 2022, type: 'Civil - Business Fraud', status: 'CONVICTED', outcome: 'Ordered to pay $354M+', description: 'Found liable for inflating asset valuations.', severity: 'high' },
      ],
      votes: [
        { bill: 'Tax Cuts and Jobs Act 2017', date: '2017-12-22', vote: 'YEA', alignsWithDonors: true, note: 'Signed $1.9T tax cut primarily benefiting corporations and wealthy donors' },
        { bill: 'Paris Climate Agreement Withdrawal', date: '2017-06-01', vote: 'NAY', alignsWithDonors: true, note: 'Withdrew US from global climate accord; aligned with API fossil fuel donors' },
      ],
      viewSummary: 'Most litigated US president in history. Four criminal indictments, one conviction on 34 felony counts, civil fraud judgments totaling $450M+. Launched personal cryptocurrency instruments days before assuming presidential power.',
      profileComplete: true,
      dataVersion: '1.0.0-seed',
      score: { total: 100, lobbyScore: 25, alignScore: 35, stockScore: 25, legalScore: 15, totalMoney: 111400000, conflictTrades: 2, donorAlignedVotes: 2, totalTrackedVotes: 2, lastUpdated: new Date().toISOString() },
    },
  ];
}

function getSeedLobbies(): Lobby[] {
  return [
    { id: 'nra',    name: 'National Rifle Association (NRA)',        shortName: 'NRA',   category: 'Firearms & Gun Rights',       color: '#dc2626', founded: 1871, mission: 'Opposes gun control legislation, promotes firearms ownership rights.', keyPositions: ['Oppose universal background checks', 'Oppose assault weapons bans'], annualSpend: 4100000, budget: '$3.2B total assets' },
    { id: 'pharma', name: 'PhRMA - Pharmaceutical Manufacturers',    shortName: 'PhRMA', category: 'Pharmaceutical Industry',      color: '#2563eb', founded: 1958, mission: 'Lobbies against Medicare drug price negotiation and drug importation.', keyPositions: ['Oppose Medicare drug price negotiation', 'Block drug importation'], annualSpend: 31700000, budget: '$500M+ annual lobbying' },
    { id: 'api',    name: 'American Petroleum Institute (API)',       shortName: 'API',   category: 'Oil & Gas / Fossil Fuels',    color: '#d97706', founded: 1919, mission: 'Lobbies against climate legislation and carbon taxes. Promotes fossil fuels.', keyPositions: ['Oppose carbon tax', 'Support fossil fuel subsidies'], annualSpend: 67000000, budget: '$200M+ annual lobbying' },
    { id: 'uscc',   name: 'U.S. Chamber of Commerce',                shortName: 'USCC',  category: 'Corporate / Business',        color: '#7c3aed', founded: 1912, mission: 'Largest US lobbying organization. Opposes wage increases and labor regulations.', keyPositions: ['Oppose minimum wage increases', 'Reduce corporate taxes'], annualSpend: 82900000, budget: '$1.5B+ since 1998' },
    { id: 'aipac',  name: 'AIPAC - American Israel Public Affairs', shortName: 'AIPAC', category: 'Foreign Policy / Israel',      color: '#0891b2', founded: 1963, mission: 'Promotes unconditional US military aid to Israel. Funds pro-Israel candidates.', keyPositions: ['Unconditional military aid to Israel', 'Oppose arms embargo'], annualSpend: 14600000, budget: '$100M+ annual lobbying' },
    { id: 'finance',name: 'Wall Street / Financial Industry',        shortName: 'Finance',category: 'Finance & Banking',           color: '#10b981', founded: 1900, mission: 'Lobbies for financial deregulation and against consumer protection measures.', keyPositions: ['Oppose Dodd-Frank regulations', 'Block fiduciary rules'], annualSpend: 95000000, budget: '$500M+ annual lobbying' },
    { id: 'defense',name: 'Defense Industry (MICC)',                 shortName: 'Defense',category: 'Defense & Aerospace',         color: '#6366f1', founded: 1950, mission: 'Promotes defense budget increases. Top contractors: Lockheed, Raytheon, Boeing.', keyPositions: ['Support defense budget increases', 'Promote weapons exports'], annualSpend: 120000000, budget: '$150M+ annual lobbying' },
    { id: 'labor',  name: 'AFL-CIO / Labor Unions',                  shortName: 'AFL-CIO',category: 'Labor / Unions',             color: '#ef4444', founded: 1886, mission: 'Supports union organizing rights, minimum wage increases, worker protections.', keyPositions: ['Support PRO Act', 'Raise minimum wage'], annualSpend: 45000000, budget: '$80M+ annual lobbying' },
    { id: 'nea',    name: 'National Education Association (NEA)',     shortName: 'NEA',   category: 'Education / Labor',           color: '#059669', founded: 1857, mission: 'Lobbies for education funding, teacher rights, opposes school vouchers.', keyPositions: ['Increase education funding', 'Oppose school vouchers'], annualSpend: 8200000, budget: '$380M annual revenue' },
  ];
}
